import {useEffect,useState} from 'react';
import {Gamepad2,Heart,RotateCcw,Sparkles,Trophy,CheckCircle2} from 'lucide-react';
import {api,errorMessage} from '../lib/api';

const truth=['What is one thing you secretly find adorable about your partner?','What is your funniest memory together?','What would your perfect surprise date look like?','What is one dream you want to achieve together?','What little habit of theirs makes you smile?'];
const dare=['Send your partner a dramatic love declaration.','Choose the next date using only emojis.','Recreate your first selfie together.','Give your partner three genuine compliments.','Do a silly 30-second dance together.'];
const gameLabels:{id:'knows'|'this-that'|'quiz'|'truth';title:string;desc:string;icon:any}[]=[
 {id:'knows',title:'Who Knows Me Better?',desc:'One answer each, then reveal the sweet truth.',icon:Heart},
 {id:'this-that',title:'This or That',desc:'Choose your side and see if you matched.',icon:Sparkles},
 {id:'quiz',title:'Couple Quiz',desc:'Ten playful questions with a gentle shared score.',icon:Trophy},
 {id:'truth',title:'Truth or Dare',desc:'Random romantic and funny prompts.',icon:Gamepad2}
];
export default function Fun(){const [game,setGame]=useState<any>('menu');const [round,setRound]=useState<any>(null);const [answer,setAnswer]=useState('');const [error,setError]=useState('');const [prompt,setPrompt]=useState('');
 const load=async(g:string)=>{setError('');setGame(g);if(g==='truth'){setPrompt(Math.random()<.5?truth[Math.floor(Math.random()*truth.length)]:dare[Math.floor(Math.random()*dare.length)]);return}try{setRound((await api.get('/games/'+g)).data);setAnswer('')}catch(e){setError(errorMessage(e))}};
 useEffect(()=>{if(game==='menu'||game==='truth')return;const id=window.setInterval(()=>{api.get('/games/'+game).then(r=>setRound(r.data)).catch(()=>{})},2500);return()=>window.clearInterval(id)},[game]);
 const submit=async()=>{if(!answer.trim())return;try{setRound((await api.post('/games/'+game+'/answer',{answer})).data);setAnswer('')}catch(e){setError(errorMessage(e))}};
 const reset=async()=>{if(game==='truth'){setPrompt('');return}try{await api.post('/games/'+game+'/reset');await load(game)}catch(e){setError(errorMessage(e))}};
 const nextTruth=()=>setPrompt(Math.random()<.5?truth[Math.floor(Math.random()*truth.length)]:dare[Math.floor(Math.random()*dare.length)]);
 return <div><p className="eyebrow">PHASE 3 · FUN</p><h1 className="font-display text-4xl font-bold">Couple games</h1><p className="mt-2 text-slate-500">Playful little games for two — never about winning, just about knowing each other.</p>{error&&<div className="alert-error mt-5">{error}</div>}
 {game==='menu'?<div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{gameLabels.map(g=><button key={g.id} onClick={()=>void load(g.id)} className="card text-left transition hover:-translate-y-1"><span className="icon-square tone-0"><g.icon size={20}/></span><h2 className="mt-5 font-display text-xl font-bold">{g.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{g.desc}</p><span className="mt-5 inline-flex text-sm font-bold text-rose-500">Play together →</span></button>)}</div>:
 <section className="card mt-7 max-w-3xl"><Header title={game==='truth'?'Truth or Dare':game==='knows'?'Who Knows Me Better?':game==='this-that'?'This or That':'Couple Quiz'} back={()=>setGame('menu')} reset={()=>void reset()}/>
 {game==='truth'?<div className="mt-7 rounded-3xl bg-gradient-to-br from-rose-50 to-violet-50 p-8 text-center"><Sparkles className="mx-auto text-violet-500"/><p className="mt-4 text-xs font-bold uppercase tracking-widest text-slate-400">Your prompt</p><h2 className="mt-3 font-display text-2xl font-bold">{prompt||'Tap below for a prompt'}</h2><button className="btn-primary mt-6" onClick={nextTruth}>Give us another</button></div>:
 <><div className="mt-7 rounded-3xl bg-gradient-to-br from-rose-50 to-violet-50 p-7"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Question</p><h2 className="mt-3 font-display text-2xl font-bold">{round?.question}</h2>{game==='this-that'&&<div className="mt-5 grid gap-3 sm:grid-cols-2">{(round?.options||[]).map((o:string)=><button key={o} onClick={()=>setAnswer(o)} className={`rounded-2xl border p-4 text-left font-semibold ${answer===o?'border-rose-400 bg-white ring-4 ring-rose-50':'border-white bg-white/70'}`}>{o}</button>)}</div>}</div>
 {!round?.revealed?<div className="mt-5"><p className="text-sm text-slate-500">{round?.isCreator?'Your answer is private until your partner answers.':'Your partner has answered. Add your answer to reveal both.'}</p>{game!=='this-that'&&<textarea className="input mt-3 min-h-28" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Write your answer…"/>}<button onClick={()=>void submit()} className="btn-primary mt-3" disabled={!answer.trim()}>{round?.isCreator?'Save my answer':'Reveal our answers'}</button></div>:<div className="mt-5 grid gap-3 sm:grid-cols-2"><AnswerCard label="First answer" value={round.creatorAnswer}/><AnswerCard label="Partner answer" value={round.partnerAnswer}/><div className="sm:col-span-2 rounded-3xl bg-emerald-50 p-5 text-center"><CheckCircle2 className="mx-auto text-emerald-500"/><p className="mt-2 font-semibold">{game==='this-that'&&round.creatorAnswer===round.partnerAnswer?'You matched! ❤️':'Lovely — you both shared an answer.'}</p>{game==='quiz'&&<p className="mt-1 text-sm text-slate-500">Keep playing to build your gentle 10-question score.</p>}</div></div>}</>}
 </section>}</div>}
function AnswerCard({label,value}:{label:string,value:string}){return <div className="rounded-3xl bg-white p-5 border border-rose-100"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 font-semibold">{value||'—'}</p></div>}
function Header({title,back,reset}:{title:string;back:()=>void;reset:()=>void}){return <div className="flex items-center justify-between"><div><button className="text-xs font-bold text-rose-500" onClick={back}>← Games</button><h2 className="mt-2 font-display text-2xl font-bold">{title}</h2></div><button className="icon-btn" onClick={reset} title="Reset"><RotateCcw size={17}/></button></div>}
