import {useEffect,useState} from 'react';
import {Plus,Trash2,CalendarDays,ImagePlus,Search,Heart,MessageCircle} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api,errorMessage} from '../lib/api';
import type {Memory} from '../types';
import Modal from '../components/Modal';
import Empty from '../components/Empty';
import {useAuth} from '../main';

const REACTIONS=[['like','👍','Like'],['love','❤️','Love'],['haha','😂','Haha'],['wow','😮','Wow'],['sad','😢','Sad'],['angry','😡','Angry']] as const;

export default function Memories(){
 const {user}=useAuth();
 const [items,setItems]=useState<Memory[]>([]),[stats,setStats]=useState<any[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[creator,setCreator]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await api.get('/memories',{params:{search:search||undefined,creator:creator||undefined}});setItems(r.data.items);setStats(r.data.stats)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(()=>{void load()},250);return()=>clearTimeout(t)},[search,creator]);
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');const f=new FormData(form);try{const r=await api.post('/memories',f,{headers:{'Content-Type':'multipart/form-data'}});setItems(x=>[r.data,...x]);setOpen(false);form.reset();void load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const del=async(id:string)=>{if(!confirm('Delete this memory?'))return;try{await api.delete('/memories/'+id);setItems(x=>x.filter(m=>m._id!==id));void load()}catch(e){setError(errorMessage(e))}};
 return <Page title="Moments" eyebrow="THE GOOD STUFF" button={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={17}/> Add moment</button>} error={error}>
  <div className="mb-6 grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="input pl-11" placeholder="Search moments, stories…"/></div><select value={creator} onChange={e=>setCreator(e.target.value)} className="input"><option value="">Everyone</option>{stats.map(s=><option key={s.userId} value={s.name}>{s.name}</option>)}</select></div>
  {stats.length>0&&<div className="mb-7 grid gap-3 sm:grid-cols-2">{stats.map(s=><div key={s.userId} className="card flex items-center justify-between p-4"><div className="flex items-center gap-3">{s.profilePicture?<img src={s.profilePicture} className="size-10 rounded-xl object-cover"/>:<div className="grid size-10 place-items-center rounded-xl bg-rose-50 text-rose-400"><Heart size={17} fill="currentColor"/> </div>}<div><p className="text-sm font-semibold">{s.name}'s moments</p><p className="text-xs text-slate-400">Uploaded by {s.name}</p></div></div><strong className="font-display text-2xl">{s.count}</strong></div>)}</div>}
  {loading?<div className="card p-10 text-center text-sm text-slate-400">♥ Loading your moments…</div>:items.length?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(m=><MomentCard key={m._id} m={m} userId={user?.id||''} onDelete={del}/>)}</div>:<Empty title="No moments found" text={search||creator?'Try another search or filter.':'Add the tiny moments, big adventures and ordinary Tuesdays you want to remember.'} action={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={16}/> Add first moment</button>}/>}<Modal open={open} onClose={()=>setOpen(false)} title="Keep a little moment"><form onSubmit={save} className="space-y-3"><input name="title" className="input" placeholder="Moment title" required/><div className="grid grid-cols-[80px_1fr] gap-3"><input name="emoji" className="input text-center text-xl" defaultValue="💗" maxLength={2}/><input name="happenedAt" className="input" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><textarea name="story" className="input min-h-32 resize-none" placeholder="What happened? How did it feel?"/><input name="locationName" className="input" placeholder="Where were you? e.g. Hunza, Lahore…"/><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-rose-200 bg-rose-50/40 p-3"><ImagePlus size={19} className="text-rose-400"/><span className="text-sm font-semibold text-slate-600">Add up to 8 gallery photos <span className="font-normal text-slate-400">(JPG, PNG, WebP)</span></span><input name="images" type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden"/></label><button disabled={busy} className="btn-primary w-full">{busy?'Saving…':'Save moment'}</button></form></Modal></Page>
}

function MomentCard({m,userId,onDelete}:{m:Memory;userId:string;onDelete:(id:string)=>void}){
 const {reactionCounts={},comments=[]}=m; const total=Object.values(reactionCounts).reduce((a,b)=>a+b,0);
 return <article className="card overflow-hidden p-0 transition hover:-translate-y-1 hover:shadow-[0_20px_50px_rgba(244,63,94,.10)]"><div className="relative">{m.imageUrl?<img src={m.imageUrl} className="h-52 w-full object-cover"/>:<div className="grid h-52 place-items-center bg-gradient-to-br from-rose-50 via-white to-violet-50 text-6xl">{m.emoji}</div>}{m.createdBy===userId&&<button onClick={()=>onDelete(m._id)} className="absolute right-4 top-4 rounded-xl bg-white/90 p-2 text-slate-300 shadow-sm transition hover:bg-rose-50 hover:text-rose-500" title="Delete moment"><Trash2 size={16}/></button>}</div><div className="p-5"><div className="flex items-center gap-3"><Avatar src={m.createdByUser?.profilePicture}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{m.createdByUser?.name||'Your partner'}</p><p className="text-[11px] text-slate-400">Uploaded this moment</p></div></div><Link to={`/memories/${m._id}`} className="mt-4 block"><div className="grid size-11 place-items-center rounded-2xl bg-rose-50 text-xl">{m.emoji}</div><h2 className="mt-3 font-display text-xl font-bold transition hover:text-rose-500">{m.title}</h2><p className="mt-1 line-clamp-2 text-sm leading-6 text-slate-500">{m.story||'No words needed.'}</p></Link><div className="mt-4 flex items-center gap-2 text-xs font-medium text-slate-400"><CalendarDays size={14}/>{new Date(m.happenedAt).toLocaleDateString(undefined,{dateStyle:'medium'})}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><div className="flex items-center gap-1">{Object.entries(reactionCounts).slice(0,4).map(([r,n])=><span key={r} className="rounded-full bg-slate-50 px-2 py-1 text-xs">{reactionEmoji(r)} {n}</span>)}{total===0&&<span className="text-xs text-slate-400">No reactions yet</span>}</div><span className="flex items-center gap-1 text-xs text-slate-400"><MessageCircle size={14}/>{comments.length}</span></div><Link to={`/memories/${m._id}`} className="btn-secondary mt-3 w-full justify-center">Open moment</Link></div></article>
}
function reactionEmoji(r:string){return ({like:'👍',love:'❤️',haha:'😂',wow:'😮',sad:'😢',angry:'😡'} as Record<string,string>)[r]||'💗'}
function Avatar({src}:{src?:string}){return src?<img src={src} className="size-9 rounded-xl object-cover"/>:<div className="grid size-9 place-items-center rounded-xl bg-rose-50 text-rose-400"><Heart size={15} fill="currentColor"/></div>}

function Page({title,eyebrow,button,error,children}:{title:string;eyebrow:string;button:React.ReactNode;error:string;children:React.ReactNode}){return <><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">{eyebrow}</p><h1 className="font-display text-4xl font-bold">{title}</h1></div>{button}</div>{error&&<div className="alert-error mt-5">{error}</div>}<div className="mt-7">{children}</div></>}
