import {useEffect,useState} from 'react';
import {BellRing,CheckCircle2,Smartphone,ShieldCheck,RefreshCw,Power} from 'lucide-react';
import {api,errorMessage} from '../lib/api';

export default function Push(){
 const [supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[permission,setPermission]=useState<NotificationPermission>('default'),[configured,setConfigured]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=async()=>{try{const ok='serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;setSupported(ok);if(!ok)return;setPermission(Notification.permission);const reg=await navigator.serviceWorker.getRegistration();const sub=await reg?.pushManager.getSubscription();setEnabled(!!sub);const key=(await api.get('/push/public-key')).data.publicKey;setConfigured(!!key)}catch(e){setError(errorMessage(e))}};
 useEffect(()=>{void refresh()},[]);
 const enable=async()=>{setBusy(true);setError('');try{const reg=await navigator.serviceWorker.register('/sw.js');const key=(await api.get('/push/public-key')).data.publicKey;if(!key)throw new Error('Push is not configured on the server yet. Add the VAPID keys to your backend environment.');const p=await Notification.requestPermission();setPermission(p);if(p!=='granted')throw new Error('Browser notifications were not allowed. You can enable them from this site’s browser permission settings.');const existing=await reg.pushManager.getSubscription();const sub=existing||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64(key)});await api.post('/push/subscribe',{subscription:sub.toJSON()});setEnabled(true)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const disable=async()=>{setBusy(true);setError('');try{const reg=await navigator.serviceWorker.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub)await sub.unsubscribe();await api.delete('/push/subscribe');setEnabled(false)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 return <div><p className="eyebrow">PHASE 4 · ALERTS</p><h1 className="font-display text-4xl font-bold">Push notifications</h1><p className="mt-2 text-slate-500">Get a browser notification when something new arrives in your private couple space.</p>{error&&<div className="alert-error mt-5">{error}</div>}
  <div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1.2fr)_minmax(280px,.8fr)]">
   <section className="card"><div className="flex items-center gap-3"><div className="icon-square tone-0"><BellRing/></div><div><h2 className="font-display text-2xl font-bold">{enabled?'Push is enabled':'Enable push alerts'}</h2><p className="text-sm text-slate-500">{enabled?'This browser is subscribed to CoupleNest push alerts.':'Turn this on once for this browser and device.'}</p></div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Status label="Browser" value={supported?'Supported':'Not supported'} ok={supported}/><Status label="Permission" value={permission==='granted'?'Allowed':permission==='denied'?'Blocked':'Not requested'} ok={permission==='granted'}/><Status label="Server" value={configured?'Configured':'Needs VAPID keys'} ok={configured}/></div>
    {supported?(enabled?<button onClick={()=>void disable()} disabled={busy} className="btn-secondary mt-6"><Power size={16}/>{busy?'Disabling…':'Disable on this device'}</button>:<button onClick={()=>void enable()} disabled={busy||!configured} className="btn-primary mt-6"><CheckCircle2 size={16}/>{busy?'Enabling…':'Enable notifications'}</button>):<div className="mt-6 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800"><Smartphone className="mb-2"/>Your current browser does not expose the Web Push API.</div>}
    <button onClick={()=>void refresh()} className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-rose-500"><RefreshCw size={13}/> Refresh status</button>
   </section>
   <section className="card"><ShieldCheck className="text-emerald-500"/><h2 className="mt-4 font-display text-xl font-bold">How you receive them</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-slate-500"><li><b>1.</b> Keep notifications enabled for this site in your browser.</li><li><b>2.</b> Open this page and click <b>Enable notifications</b>.</li><li><b>3.</b> Your browser stores a private push subscription.</li><li><b>4.</b> When your partner reacts, comments, sends a letter, adds a task, or another supported event happens, CoupleNest sends a browser notification.</li></ol><div className="mt-5 rounded-2xl bg-rose-50 p-4 text-xs leading-5 text-rose-700">For Vercel production, add <b>VAPID_PUBLIC_KEY</b>, <b>VAPID_PRIVATE_KEY</b> and <b>VAPID_SUBJECT</b> to the backend environment. Never expose the private key in the frontend.</div></section>
  </div></div>
}
function Status({label,value,ok}:{label:string;value:string;ok:boolean}){return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className={`mt-1 text-sm font-bold ${ok?'text-emerald-600':'text-slate-500'}`}>{ok?'✓ ':''}{value}</p></div>}
function urlBase64(s:string){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
