import {useEffect,useMemo,useState} from 'react';
import {Heart,RefreshCw,Send,Smile,Gift,MessageCircle,CalendarDays} from 'lucide-react';
import {api,errorMessage} from '../lib/api';
import {useAuth} from '../main';

const moods=['😍','😊','😐','🥹','😔','😡'];
export default function Rituals(){
 const {user}=useAuth(); const [data,setData]=useState<any>({question:'',moods:[],answers:[],loveNotes:[]}); const [history,setHistory]=useState<any>({moods:[],answers:[]}); const [answer,setAnswer]=useState(''); const [note,setNote]=useState(''); const [days,setDays]=useState(30); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const load=async()=>{try{setError('');const [a,b]=await Promise.all([api.get('/rituals'),api.get('/rituals/history',{params:{days}})]);setData(a.data);setHistory(b.data)}catch(e){setError(errorMessage(e))}};
 useEffect(()=>{void load()},[days]);
 const myAnswer=data.answers?.find((x:any)=>String(x.userId?._id||x.userId)===user?.id); const partnerAnswer=data.answers?.find((x:any)=>String(x.userId?._id||x.userId)!==user?.id); const bothAnswered=Boolean(myAnswer&&partnerAnswer);
 const sendAnswer=async()=>{if(!answer.trim())return;setBusy(true);try{await api.post('/rituals/answer',{questionKey:data.question,answer});setAnswer('');await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const addNote=async()=>{if(!note.trim())return;setBusy(true);try{await api.post('/rituals/love-note',{body:note});setNote('');await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const pickMood=async(mood:string)=>{try{await api.post('/rituals/mood',{mood});await load()}catch(e){setError(errorMessage(e))}};
 const randomNote=useMemo(()=>{const a=data.loveNotes||[];return a.length?a[Math.floor(Math.random()*a.length)]:null},[data.loveNotes]);
 const moodRows=useMemo(()=>{const map=new Map<string,any>();for(const m of history.moods||[]){const key=String(m.dayKey);const row=map.get(key)||{day:key,items:[]};row.items.push(m);map.set(key,row)}return [...map.values()].slice(-14)},[history.moods]);
 return <div className="space-y-7"><div><p className="eyebrow">LITTLE WAYS TO STAY CLOSE</p><div className="flex items-end justify-between gap-4"><div><h1 className="font-display text-4xl font-bold">Daily rituals</h1><p className="mt-2 text-slate-500">Tiny check-ins that make your private corner feel alive.</p></div><button className="btn-secondary" onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></div></div>{error&&<div className="alert-error">{error}</div>}
 <section className="grid gap-5 xl:grid-cols-3">
  <div className="card xl:col-span-2"><div className="flex items-start gap-3"><div className="icon-square tone-0"><MessageCircle size={19}/></div><div className="min-w-0"><p className="eyebrow">DAILY Q&amp;A</p><h2 className="font-display text-2xl font-bold">{data.question||'A little question for you two'}</h2><p className="mt-1 text-sm text-slate-500">Answer first, then reveal each other's answer.</p></div></div><div className="mt-5 flex gap-2"><textarea className="input min-h-28 resize-none" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={myAnswer?'You already answered today.':'Write your answer…'} disabled={Boolean(myAnswer)}/><button onClick={sendAnswer} disabled={busy||!!myAnswer||!answer.trim()} className="btn-primary self-end px-4"><Send size={16}/></button></div>{myAnswer&&<p className="mt-2 text-xs font-semibold text-emerald-600">✓ Your answer is saved.</p>}{bothAnswered?<div className="mt-5 grid gap-3 md:grid-cols-2"><AnswerCard answer={myAnswer} mine/><AnswerCard answer={partnerAnswer}/></div>:<div className="mt-5 rounded-2xl bg-rose-50/70 p-4 text-sm text-rose-700">The answers will reveal when you both answer. 💗</div>}</div>
  <div className="card"><div className="flex items-center gap-3"><div className="icon-square tone-1"><Smile size={19}/></div><div><p className="eyebrow">MOOD CHECK</p><h2 className="font-display text-2xl font-bold">How are we?</h2></div></div><div className="mt-5 grid grid-cols-3 gap-2">{moods.map(m=><button key={m} onClick={()=>void pickMood(m)} className={`rounded-2xl border p-3 text-2xl transition ${data.moods?.find((x:any)=>String(x.userId?._id||x.userId)===user?.id)?.mood===m?'border-rose-300 bg-rose-50 scale-105':'border-slate-100 bg-white hover:bg-rose-50'}`}>{m}</button>)}</div><div className="mt-5 space-y-3">{(data.moods||[]).map((m:any)=><div key={String(m.userId?._id||m.userId)} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><span className="text-xl">{m.mood}</span><div><p className="text-sm font-semibold">{m.userId?.name||'Partner'}</p><p className="text-xs text-slate-400">Today's mood</p></div></div>)}</div></div>
 </section>
 <section className="grid gap-5 lg:grid-cols-2"><div className="card"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="icon-square tone-2"><Gift size={19}/></div><div><p className="eyebrow">LOVE JAR</p><h2 className="font-display text-2xl font-bold">A note for you</h2></div></div><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={16}/></button></div><div className="mt-5 min-h-28 rounded-3xl bg-gradient-to-br from-rose-50 to-violet-50 p-5"><p className="font-display text-xl leading-8 text-slate-700">{randomNote?`“${randomNote.body}”`:'Your jar is waiting for its first little love note.'}</p></div><div className="mt-3 flex gap-2"><input className="input" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note to the jar…"/><button disabled={busy||!note.trim()} onClick={addNote} className="btn-primary px-4"><Heart size={16} fill="currentColor"/></button></div></div><div className="card"><div className="flex items-center justify-between"><div><p className="eyebrow">HISTORY</p><h2 className="font-display text-2xl font-bold">Mood history</h2></div><select className="input w-auto" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div><div className="mt-5 space-y-3">{moodRows.length?moodRows.map((row:any)=><div key={row.day} className="flex items-center gap-3"><span className="w-20 text-xs text-slate-400">{row.day}</span><div className="flex gap-2">{row.items.map((m:any)=><span key={String(m.userId?._id||m.userId)} title={m.userId?.name}>{m.mood}</span>)}</div></div>):<p className="text-sm text-slate-400">Mood history will appear here after your first check-in.</p>}</div></div></section>
 </div>
}
function AnswerCard({answer,mine}:{answer:any;mine?:boolean}){return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-400">{mine?'Your answer':answer.userId?.name||'Partner'}</p><p className="mt-2 text-sm leading-6 text-slate-700">{answer.answer}</p></div>}
