import {useState} from 'react';
import {Copy,Check,Heart,LogOut,Save,Camera,Link2,Clock3,Unlink} from 'lucide-react';
import {api,errorMessage,clearAuthToken} from '../lib/api';
import {useAuth} from '../main';
import {useNavigate} from 'react-router-dom';

const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const toLocalInput=(value?:string)=>{if(!value)return '';const d=new Date(value);if(Number.isNaN(+d))return '';const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};

export default function Settings(){
 const {user,couple,refresh}=useAuth();
 const [name,setName]=useState(user?.name||''),[age,setAge]=useState(String(user?.age||'')),[gender,setGender]=useState(user?.gender||''),[birthDay,setBirthDay]=useState(String(user?.birthDay||'')),[birthMonth,setBirthMonth]=useState(String(user?.birthMonth||''));
 const [spaceName,setSpaceName]=useState(couple?.name||''),[fellInLoveAt,setFellInLoveAt]=useState(toLocalInput(couple?.fellInLoveAt||couple?.anniversary)),[coverQuote,setCoverQuote]=useState(couple?.coverQuote||'Together is a wonderful place to be.'),[partnerCode,setPartnerCode]=useState('');
 const [copied,setCopied]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[photo,setPhoto]=useState<File|null>(null),[busy,setBusy]=useState(false),[connecting,setConnecting]=useState(false);
 const nav=useNavigate();
 const saveProfile=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{const f=new FormData();f.append('name',name);f.append('age',age);f.append('gender',gender);f.append('birthDay',birthDay);f.append('birthMonth',birthMonth);if(photo)f.append('profilePicture',photo);await api.patch('/profile',f,{headers:{'Content-Type':'multipart/form-data'}});await refresh();setPhoto(null);setMsg('Profile saved beautifully.');setTimeout(()=>setMsg(''),2500)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const saveCouple=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{await api.patch('/couple',{name:spaceName,fellInLoveAt:fellInLoveAt?new Date(fellInLoveAt).toISOString():undefined,coverQuote});await refresh();setMsg('Your love story is updated.');setTimeout(()=>setMsg(''),2500)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const connect=async(e:React.FormEvent)=>{e.preventDefault();setError('');setConnecting(true);try{await api.post('/couple/connect',{inviteCode:partnerCode.trim().toUpperCase()});await refresh();setPartnerCode('');setMsg('Partner request sent. They will receive an email and must confirm it from their dashboard before you become partners.');setTimeout(()=>setMsg(''),3000)}catch(e){setError(errorMessage(e))}finally{setConnecting(false)}};
 const copy=()=>{navigator.clipboard?.writeText(couple?.inviteCode||'');setCopied(true);setTimeout(()=>setCopied(false),1500)};
 const logout=async()=>{await api.post('/auth/logout');clearAuthToken();await refresh();nav('/login')};
 return <><p className="eyebrow">YOUR PRIVATE SPACE</p><h1 className="font-display text-4xl font-bold">Settings</h1>{error&&<div className="alert-error mt-5">{error}</div>}{msg&&<div className="alert-success mt-5">{msg}</div>}
 <div className="mt-7 grid gap-5 lg:grid-cols-2">
 <section className="card"><div className="mb-5 flex items-center gap-3"><div className="relative">{user?.profilePicture?<img src={user.profilePicture} className="size-14 rounded-2xl object-cover"/>:<div className="grid size-14 place-items-center rounded-2xl bg-rose-50 text-rose-400"><Heart fill="currentColor"/></div>}<label className="absolute -bottom-2 -right-2 grid size-8 cursor-pointer place-items-center rounded-full bg-white text-rose-500 shadow-md"><Camera size={15}/><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label></div><div><h2 className="font-semibold">Your profile</h2><p className="text-xs text-slate-400">Personal details and your birthday reminder.</p></div></div>
 <form onSubmit={saveProfile} className="space-y-4"><label className="field"><span>Name</span><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></label><label className="field"><span>Email</span><input className="input bg-slate-50" value={user?.email||''} readOnly/></label><div className="grid grid-cols-2 gap-3"><label className="field"><span>Gender</span><select className="input" value={gender} onChange={e=>setGender(e.target.value)} required><option value="">Select gender</option><option value="female">Female</option><option value="male">Male</option><option value="non-binary">Non-binary</option><option value="prefer-not-to-say">Prefer not to say</option></select></label><label className="field"><span>Age</span><input className="input" type="number" min={13} max={120} value={age} onChange={e=>setAge(e.target.value)} required/></label></div><div><span className="mb-2 block text-xs font-semibold text-slate-500">Birthday</span><div className="grid grid-cols-2 gap-3"><select className="input" value={birthDay} onChange={e=>setBirthDay(e.target.value)} required><option value="">Day</option>{Array.from({length:31},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select><select className="input" value={birthMonth} onChange={e=>setBirthMonth(e.target.value)} required><option value="">Month</option>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></div><p className="mt-2 text-xs text-slate-400">Only day/month are stored. Your partner gets birthday reminders starting 7 days before.</p></div>{photo&&<p className="text-xs font-semibold text-rose-500">New photo selected: {photo.name}</p>}<button disabled={busy} className="btn-primary"><Save size={16}/>{busy?'Saving…':'Save profile'}</button></form></section>
 <section className="card"><div className="mb-5 flex items-center gap-3"><div className="icon-square tone-0"><Heart size={18} fill="currentColor"/></div><div><h2 className="font-semibold">Our love story</h2><p className="text-xs text-slate-400">Set the exact moment your story began.</p></div></div>
 <form onSubmit={saveCouple} className="space-y-4"><label className="field"><span>Space name</span><input className="input" value={spaceName} onChange={e=>setSpaceName(e.target.value)} required/></label><label className="field"><span>When we fell in love</span><input className="input" type="datetime-local" value={fellInLoveAt} onChange={e=>setFellInLoveAt(e.target.value)}/></label><label className="field"><span>Dashboard quote</span><input className="input" value={coverQuote} maxLength={180} onChange={e=>setCoverQuote(e.target.value)} placeholder="Together is a wonderful place to be."/></label><button disabled={busy} className="btn-primary"><Save size={16}/> Save our story</button></form>
 <div className="mt-7 rounded-2xl border border-rose-100 bg-rose-50/60 p-4"><div className="flex items-center gap-3"><Clock3 className="text-rose-500" size={18}/><div><p className="font-semibold">Love timer</p><p className="text-xs text-slate-500">The dashboard can show your time together in years, months, days, hours, minutes or seconds.</p></div></div></div>
 <div className="mt-7 border-t border-slate-100 pt-6"><div className="flex items-center gap-3"><Link2 className="text-rose-400" size={19}/><div><h2 className="font-display text-2xl font-bold">Connect your partner</h2><p className="mt-1 text-sm text-slate-500">Enter their code. We will email them your name and email, and they must confirm the request from their dashboard.</p></div></div><form onSubmit={connect} className="mt-4 flex gap-2"><input className="input font-mono uppercase tracking-[.18em]" placeholder="PARTNER CODE" value={partnerCode} onChange={e=>setPartnerCode(e.target.value.toUpperCase())} maxLength={20} required/><button disabled={connecting} className="btn-primary shrink-0">{connecting?'Connecting…':'Connect'}</button></form>{couple?.outgoingPartnerRequest&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>Waiting for {couple.outgoingPartnerRequest.recipientName || 'your partner'} to confirm.</b><p className="mt-1 text-amber-800/70">A confirmation email was sent to {couple.outgoingPartnerRequest.recipientEmail}. You are not connected until they accept.</p></div>}{couple?.pendingPartnerRequest&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>Waiting for {couple.pendingPartnerRequest.requesterName || 'partner'} to confirm.</b><p className="mt-1 text-amber-800/70">They were notified by email. You are not connected yet.</p></div>}{couple?.partner&&<div className="mt-4 flex items-center gap-3 rounded-2xl bg-emerald-50 p-4 text-sm">{couple.partner.profilePicture?<img src={couple.partner.profilePicture} className="size-11 rounded-xl object-cover"/>:<div className="grid size-11 place-items-center rounded-xl bg-white text-emerald-500"><Heart size={16} fill="currentColor"/></div>}<div className="min-w-0"><b>Connected ♥</b><p className="mt-1 truncate text-emerald-700/70">{couple.partner.name} · {couple.partner.email}</p></div><Unlink size={16} className="ml-auto text-emerald-500"/></div>}{!couple?.partner&&<p className="mt-3 text-xs text-slate-400">Tip: connect before creating shared memories so your existing empty space can merge into your partner's space.</p>}</div>
 <div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Your invite code</p><div className="mt-3 flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><code className="flex-1 px-2 font-mono text-lg tracking-[.25em]">{couple?.inviteCode}</code><button onClick={copy} className="btn-secondary">{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy'}</button></div></div>
 <div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Signed in as</p><p className="mt-1 font-semibold">{user?.name}</p><p className="text-sm text-slate-500">{user?.email}</p><button onClick={logout} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-rose-500"><LogOut size={16}/> Sign out</button></div></section></div></>;
}
