import {NavLink, Outlet, useNavigate, Link} from 'react-router-dom';
import {useEffect,useState} from 'react';
import {motion, AnimatePresence} from 'framer-motion';
import {Heart, Home, Image, CheckSquare, CalendarDays, BookHeart, Settings, Menu, X, LogOut, Sparkles, MessageCircle, Cake, Bell, HeartHandshake, Mail, MapPin, BarChart3,WalletCards,Gamepad2,Music2,Gift,ListTodo,UserRound,ShieldCheck,Palette,BellRing,Smartphone,Clock, Trash2} from 'lucide-react';
import {api} from '../lib/api';
import {useAuth} from '../main';

const links = [
  ['/','Home',Home], ['/memories','Memories',Image], ['/bucket-list','Bucket list',CheckSquare],
  ['/dates','Dates',CalendarDays], ['/journal','Journal',BookHeart], ['/messages','Messages',MessageCircle], ['/rituals','Daily rituals',HeartHandshake], ['/letters','Open When',Mail], ['/timeline','Our timeline',HeartHandshake], ['/places','Places',MapPin], ['/stats','Our stats',BarChart3], ['/notifications','Notifications',Bell], ['/settings','Settings',Settings], ['/games','Couple games',Gamepad2], ['/playlist','Playlist',Music2], ['/wishlist','Wishlist',Gift], ['/tasks','Shared tasks',ListTodo], ['/expenses','Trip expenses',WalletCards], ['/couple-profile','Couple profile',UserRound], ['/privacy','Privacy center',ShieldCheck], ['/themes','Themes',Palette], ['/push','Push alerts',BellRing], ['/pwa','Install app',Smartphone]
] as const;

type LatestNotification = { _id:string; title:string; body:string; link?:string; createdAt:string; read:boolean; actorId?:{name?:string;profilePicture?:string} };

export default function AppLayout(){
  const [open,setOpen]=useState(false); const [unread,setUnread]=useState(0); const [messageUnread,setMessageUnread]=useState(0); const [latest,setLatest]=useState<LatestNotification|null>(null); const [showLatest,setShowLatest]=useState(true); const [latestOpen,setLatestOpen]=useState(false);
  const nav=useNavigate(); const {couple,user,refresh}=useAuth();
  const logout=async()=>{await api.post('/auth/logout');await refresh();nav('/login')};

  const loadBadges=async()=>{
    try{const [n,m]=await Promise.all([api.get('/notifications'),api.get('/messages/unread-count')]);const items=Array.isArray(n.data.items)?n.data.items:[];setUnread(Number(n.data.unread||0));setMessageUnread(Number(m.data.count||0));setLatest(items[0]||null)}catch{}
  };
  useEffect(()=>{let alive=true;const load=async()=>{try{const [n,m]=await Promise.all([api.get('/notifications'),api.get('/messages/unread-count')]);if(!alive)return;const items=Array.isArray(n.data.items)?n.data.items:[];setUnread(Number(n.data.unread||0));setMessageUnread(Number(m.data.count||0));setLatest(items[0]||null)}catch{}};void load();const timer=window.setInterval(load,5000);return()=>{alive=false;window.clearInterval(timer)}},[]);

  const clearNotifications=async()=>{try{await api.delete('/notifications');setUnread(0);setLatest(null);setLatestOpen(false)}catch{}};
  const navItems=links.map(([to,label,Icon])=><NavLink onClick={()=>setOpen(false)} key={to} to={to} className={({isActive})=>`nav-link ${isActive?'nav-active':''}`}><Icon size={19}/><span className="min-w-0 flex-1">{label}</span>{to==='/messages'&&messageUnread>0&&<span className="grid min-w-5 place-items-center rounded-full bg-rose-500 px-1.5 py-0.5 text-[10px] font-bold text-white">{messageUnread>99?'99+':messageUnread}</span>}{to==='/notifications'&&unread>0&&<span className="grid min-w-5 place-items-center rounded-full bg-rose-500 px-1.5 py-0.5 text-[10px] font-bold text-white">{unread>99?'99+':unread}</span>}</NavLink>);
  return <div className="min-h-screen bg-[var(--cn-bg)] text-slate-800">
    <aside className="fixed inset-y-0 left-0 z-40 hidden h-screen w-72 flex-col overflow-hidden border-r border-rose-100 bg-white/85 px-5 py-6 backdrop-blur-xl lg:flex">
      <Brand/><div className="mt-6 flex shrink-0 items-center gap-3 rounded-2xl border border-rose-100 bg-rose-50/60 p-3"><Avatar src={user?.profilePicture}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{couple?.name||'Our space'}</p><p className="flex items-center gap-1 text-[11px] text-slate-400"><Cake size={12}/> Private couple space</p></div></div><div className="mt-5 min-h-0 flex-1 space-y-2 overflow-y-auto pr-1 [scrollbar-width:thin]">{navItems}</div>
      <div className="mt-4 shrink-0"><div className="rounded-3xl bg-gradient-to-br from-rose-50 to-violet-50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles size={16}/> Your little corner</div><p className="mt-1 text-xs leading-5 text-slate-500">{couple?.name||'Our space'} is private to you two.</p></div><button onClick={logout} className="mt-3 nav-link w-full text-slate-500"><LogOut size={18}/> Sign out</button></div>
    </aside>
    <header className="sticky top-0 z-30 border-b border-rose-100/80 bg-white/90 px-4 py-3 backdrop-blur-xl lg:hidden"><div className="flex items-center justify-between gap-3"><Brand compact={false}/><div className="flex items-center gap-1"><button onClick={()=>setLatestOpen(v=>!v)} className="relative grid size-11 place-items-center rounded-2xl text-slate-600 transition hover:bg-rose-50 hover:text-rose-500" aria-label="Latest notification"><Bell size={20}/>{unread>0&&<span className="absolute right-1.5 top-1.5 grid min-w-4 place-items-center rounded-full bg-rose-500 px-1 text-[9px] font-bold leading-4 text-white ring-2 ring-white">{unread>99?'99+':unread}</span>}</button><button className="icon-btn" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'}>{open?<X/>:<Menu/>}</button></div></div>
      <AnimatePresence>{latestOpen&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="absolute inset-x-3 top-[calc(100%+8px)] overflow-hidden rounded-3xl border border-rose-100 bg-white shadow-xl shadow-rose-100/40">
        <div className="flex items-center justify-between border-b border-rose-100 bg-rose-50/50 px-4 py-3"><div><p className="text-sm font-bold">Latest notification</p><p className="text-[10px] text-slate-400">Messages use the separate chat badge.</p></div><button onClick={()=>setLatestOpen(false)} className="rounded-xl p-2 text-slate-400 hover:bg-white" aria-label="Hide latest notification"><X size={16}/></button></div>
        {showLatest&&latest?<div className="p-4"><div className="flex gap-3"><div className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-2xl bg-rose-50 text-rose-500">{latest.actorId?.profilePicture?<img src={latest.actorId.profilePicture} className="size-full object-cover" alt=""/>:<Bell size={18}/>}</div><div className="min-w-0 flex-1"><p className="font-semibold">{latest.title}</p><p className="mt-1 text-sm leading-5 text-slate-500">{latest.body}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-slate-400"><Clock size={11}/>{new Date(latest.createdAt).toLocaleString()}</p></div></div><div className="mt-4 flex items-center gap-2"><button onClick={()=>setShowLatest(false)} className="btn-secondary flex-1 text-xs">Hide</button>{latest.link&&<Link to={latest.link} onClick={()=>setLatestOpen(false)} className="btn-primary flex-1 text-center text-xs">Open</Link>}<button onClick={()=>void clearNotifications()} className="grid size-10 place-items-center rounded-xl border border-rose-100 text-rose-500 hover:bg-rose-50" title="Clear all notifications" aria-label="Clear all notifications"><Trash2 size={15}/></button></div></div>:<div className="p-5 text-center"><Bell className="mx-auto text-rose-300" size={24}/><p className="mt-2 text-sm font-semibold">No notifications</p><p className="mt-1 text-xs text-slate-400">{showLatest?'You are all caught up.':'The latest notification is hidden.'}</p>{!showLatest&&<button onClick={()=>setShowLatest(true)} className="mt-3 text-xs font-semibold text-rose-500">Show latest</button>}</div>}
      </motion.div>}</AnimatePresence>
    </header>
    <AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} className="fixed inset-x-0 top-[65px] z-30 max-h-[calc(100vh-65px)] overflow-y-auto bg-white p-4 shadow-xl lg:hidden"><div className="space-y-1">{navItems}</div></motion.div>}</AnimatePresence>
    <MobileBottomNav unread={unread} messageUnread={messageUnread}/>
    <main className="w-full px-4 py-6 pb-24 lg:ml-72 lg:w-[calc(100%-18rem)] lg:max-w-none lg:px-8 lg:py-10 lg:pb-10"><Outlet/></main>
  </div>
}

function MobileBottomNav({unread,messageUnread}:{unread:number;messageUnread:number}){
  const items=[['/','Home',Home],['/memories','Memories',Image],['/messages','Messages',MessageCircle],['/dates','Dates',CalendarDays],['/notifications','Alerts',Bell]] as const;
  return <nav aria-label="Quick navigation" className="fixed inset-x-0 bottom-0 z-50 border-t border-rose-100/80 bg-white/95 px-2 pb-[calc(.5rem+env(safe-area-inset-bottom))] pt-2 shadow-[0_-10px_35px_rgba(244,63,94,.10)] backdrop-blur-xl lg:hidden"><div className="mx-auto grid max-w-md grid-cols-5 items-end">{items.map(([to,label,Icon],index)=>{const center=index===2;return <NavLink key={to} to={to} aria-label={label} className="group relative flex min-w-0 flex-col items-center justify-end gap-1 text-[10px] font-semibold">{({isActive})=><><span className={center?`relative -mt-8 grid size-14 place-items-center rounded-[1.35rem] border-4 border-white bg-gradient-to-br from-rose-400 to-fuchsia-500 text-white shadow-lg shadow-rose-200 transition-transform group-active:scale-95 ${isActive?'scale-105':''}`:`relative grid size-9 place-items-center rounded-xl transition ${isActive?'bg-rose-50 text-rose-500':'text-slate-400 group-hover:bg-rose-50 group-hover:text-rose-500'}`}><Icon size={center?23:20} strokeWidth={center?2.4:2}/>{to==='/messages'&&messageUnread>0&&<span className="absolute -right-1 -top-1 grid min-w-4 place-items-center rounded-full bg-rose-500 px-1 text-[9px] font-bold leading-4 text-white ring-2 ring-white">{messageUnread>99?'99+':messageUnread}</span>}{to==='/notifications'&&unread>0&&<span className="absolute -right-1 -top-1 grid min-w-4 place-items-center rounded-full bg-rose-500 px-1 text-[9px] font-bold leading-4 text-white ring-2 ring-white">{unread>99?'99+':unread}</span>}</span><span className={center?'pb-0.5 text-rose-500':isActive?'text-rose-500':'text-slate-400'}>{label}</span></>}</NavLink>})}</div></nav>
}
function Avatar({src}:{src?:string}){return src?<img src={src} className="size-10 rounded-xl object-cover"/>:<div className="grid size-10 place-items-center rounded-xl bg-white text-rose-400"><Heart size={17} fill="currentColor"/></div>}
function Brand({compact=false}:{compact?:boolean}){return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-rose-400 to-fuchsia-500 text-white shadow-lg shadow-rose-200"><Heart size={19} fill="currentColor"/></div>{!compact&&<div><div className="font-display text-xl font-bold">CoupleNest</div><div className="text-[11px] text-slate-400">your private little world</div></div>}</div>}
